spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventorydb
    username: root
    password: 2477
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

    application:
    name: sigi-backend

jwt:
  secret: U3ByaW5nQm9vdC1TZWNyZXRLZXktMTIzIT8kQCM=
  access:
    expiresSeconds: 5000 # 15 min

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.sigi: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: inventory-service

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
